---
title: "HW 2 Solutions"
author: "Tom Fletcher"
date: "September 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

__This solution set is for use by students in CS 3130 / ECE 3530 in Fall 2017 ONLY. Distribution outside of the class will be considered cheating.__

# Problem 1

## (a)

$\Omega = \{1, 2, 3, 4, 5, 6\}$

$A = \{3, 4, 5, 6\}$

$B = \{1, 3, 5\}$

$A \cap B = \{3, 5\}$

The probabilities are:

$P(A) = \frac{2}{3}$

$P(B) = \frac{1}{2}$

$$P(A \cap B) = \frac{1}{3} = \frac{2}{3} \times \frac{1}{2} = P(A) \times P(B)$$

So, these events are __independent__.

## (b)

$\Omega = \{HHH, HHT, HTH, HTT, THH, THT, TTH, TTT\}$

$A = \{HHH, HHT, HTT, THH, TTH, TTT\}$

$B = \{HHH, HHT, HTH, HTT, THH, THT, TTH\}$

$A \cap B = \{HHH, HHT, HTT, THH, TTH\}$

The probabilities are:

$P(A) = \frac{6}{8} = \frac{3}{4}$

$P(B) = \frac{7}{8}$

$P(A \cap B) = \frac{5}{8} \neq \frac{3}{4} \times \frac{7}{8} = P(A) \times P(B)$

So, these events are __dependent__ (that is, __not independent__).

# Problem 2

Let $S$ be the event that a person is a smoker, and let $C$ be the event that a person has lung cancer. We'll first list what information is given in the problem. We know:

* $P(C) = 0.0013$
* $P(S \mid C) = 0.9$
* $P(S \mid C^c) = 0.169$

## (a)
This question is asking: what is $P(C | S)$. We need to use Bayes' Rule, and put it into a form where we have all of the needed probabilities:

$$
\begin{align}
P(C \mid S) &= \frac{P(S \mid C) P(C)}{P(S)} & \text{Bayes' Rule}\\
         &= \frac{P(S \mid C) P(C)}{P(S \mid C)P(C) + P(S \mid C^c)P(C^c)} & \text{Total Probability}\\
         &= \frac{P(S \mid C) P(C)}{P(S \mid C)P(C) + P(S \mid C^c)(1 - P(C))} & \text{Complement Rule}\\
         &= \frac{0.9 \times 0.0013}{0.9 \times 0.0013 + 0.169 \times (1 - 0.0013)} & \text{plugging in probabilities}\\
         &= `r (0.9 * 0.0013) / (0.9 * 0.0013 + 0.169 * (1 - 0.0013))` & \\
\end{align}
$$

## (b)
Now the problem is asking for $P(C \mid S^c)$.

$$
\begin{align}
P(C \mid S^c) &= \frac{P(S^c \mid C) P(C)}{P(S^c)} & \text{Bayes' Rule}\\
              &= \frac{(1 - P(S \mid C)) P(C)}{1 - P(S)} & \text{Complement Rule}\\
              &= \frac{(1 - 0.9) \times 0.0013}{1 - (0.9 \times 0.0013 + 0.169 \times (1 - 0.0013))} & \text{plugging in numbers}\\
              &= `r (1 - 0.9) * 0.0013 / (1 - (0.9 * 0.0013 + 0.169 * (1 - 0.0013)))` & \\
\end{align}
$$

Notice that smokers have about a 40 times higher chance to get lung cancer than non-smokers!

# Problem 3

As always, we first define the notation for our events:

* $R_1$ = "I pick red"
* $G_1$ = "I pick green"
* $R_2$ = "You pick red"
* $G_2$ = "You pick green"

## (a)

 First Events    | Second Events           | Joint Probabilities     |
-----------------|-------------------------|-------------------------|
 $P(R_1) = 0.5$  | $P(R_2 \mid R_1) = 2/3$ | $P(R_1 \cap R_2) = 1/3$ |
 <br>            | $P(G_2 \mid R_1) = 1/3$ | $P(R_1 \cap G_2) = 1/6$ |
 $P(G_1) = 0.5$  | $P(R_2 \mid G_1) = 1/3$ | $P(G_1 \cap R_2) = 1/6$ |
 <br>            | $P(G_2 \mid G_1) = 2/3$ | $P(G_1 \cap G_2) = 1/3$ |

## (b)
Using _total probability_, we get
$$P(R_2) = P(R_1 \cap R_2) + P(G_1 \cap R_2) = 1/3 + 1/6 = 0.5$$

## (c)
Note: $A = G_1$, $B = R_2$.

$$P(A \cap B) = P(G_1 \cap R_2) = 1/6 \neq 1/4 = P(G_1) P(R_2)$$
So, these events are _dependent_.

## (d)

Using Bayes' Rule:

$$
\begin{align}
P(R_1 \mid R_2) &= \frac{P(R_2 \mid R_1) P(R_1)}{P(R_2)}\\
                &= \frac{(2/3) \times (1/2)}{0.5}\\
                &= \frac{2}{3}
\end{align}
$$
# Problem 4

## (a)

The question is asking for $P(D \mid T)$. Using Bayes' rule, we have

$$
\begin{align*}
P(D \mid T) &= \frac{P(T \mid D) P(D)}{P(T)} & \text{Bayes' rule}\\
            &= \frac{P(T \mid D) P(D)}{P(T \mid D) P(D) + P(T \mid D^c) P(D^c)} & \text{Total probability}\\
            &= \frac{P(T \mid D) P(D)}{P(T \mid D) P(D) + (1 - P(T^c \mid D^c)) (1 - P(D))} & \text{Complement rule}\\
            &= \frac{0.98 \times 0.01}{0.98 \times 0.01 + (1 - 0.95) \times (1 - 0.01)} & \text{plugging in given probabilities}\\
            &= `r (0.98 * 0.01) / (0.98 * 0.01 + (1 - 0.95)*(1 - 0.01))` & \\
\end{align*}
$$

## (b)

Let $T_1$ be the event that the first test returns positive and $T_2$ be the event that the second test returns positive.

$$
\begin{align}
P(D \mid T_1 \cap T_2) &= \frac{P(T_1 \cap T_2 \mid D) P(D)}{P(T_1 \cap T_2)} & \text{Bayes' rule}\\
                       &= \frac{P(T_1 \mid D) P(T_2 \mid D) P(D)}{P(T_1 \cap T_2)} & \text{Using independence of $T_1$ and $T_2$ given disease}\\
                       &= \frac{P(T_1 \mid D) P(T_2 \mid D) P(D)}{P(T_1 \cap T_2 \mid D) P(D) + P(T_1 \cap T_2 \mid D^c) P(D^c)} & \text{Total probability}\\
                       &= \frac{P(T_1 \mid D) P(T_2 \mid D) P(D)}{P(T_1 \mid D) P(T_2 \mid D) P(D) + P(T_1 \mid D^c) P(T_2 \mid D^c) P(D^c)} & \text{Using independence of $T_1$ and $T_2$ given disease}\\
                       &= \frac{0.98 \times 0.98 \times 0.01}{(0.98 \times 0.01 + (1 - 0.95) \times (1 - 0.01))^2} & \text{plugging in probabilities}\\
                       &= `r 0.98 * 0.98 * 0.01 / (0.98 * 0.98 * 0.01 + (1 - 0.95) * (1 - 0.95) * (1 - 0.01))` & \\
\end{align}
$$